# The URL the site will be built for
base_url = "https://dmcgaa.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Put all your custom variables here
[extra]
author = "dmcgaa"
year = "2021"

title = "dmcgaa"
description = "Homepage for dmcgaa"
build_search_index = true
generate_rss = true
highlight_theme = "base16-ocean-light"

default_language = "en"

taxonomies = [
  {name="tags", rss=true},
  {name="categories", rss=true},
]

keywords = "zola, theme, retro, hacking"

[translations.en]
about = "About"
home = "Home"
tags = "Tags"
archive = "Archive"
links = "Links"
next_page = "Next Page"
last_page = "Last Page"

[extra.social]
github = "dmcgaa"
twitter = "dmcgaa"
#facebook = ""
#instagram = ""
#dribbble = ""
#weibo = ""

[extra.show]
tags = false
links = true

